[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socketio-handler/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
