export const GAME_ACTIONS = {
  PLAY_MOVE: 'PLAY_MOVE',
  DEAL_NEW_CARDS: 'DEAL_NEW_CARDS', 
  END_ROUND: 'END_ROUND',
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  START_NEW_MATCH: 'START_NEW_MATCH'
} as const;